/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hepJ9RzXz2O
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/app/ui/label"
import { Input } from "@/app/ui/input"
import { Textarea } from "@/app/ui/textarea"
import { Button } from "@/app/ui/button"
import Link from "next/link"

export function ContactPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <div className="flex-grow bg-background px-4 py-12 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Get in touch</h2>
          <p className="mt-4 text-lg leading-6 text-muted-foreground">
            Have a question or want to work together? Fill out the form below and we&apos;ll get back to you as soon as
            possible.
          </p>
        </div>
        <div className="mx-auto mt-8 max-w-md">
          <form className="space-y-6">
            <div className="grid grid-cols-2 gap-x-6">
              <div className="space-y-2">
                <Label htmlFor="first-name">First name</Label>
                <Input id="first-name" placeholder="John" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="last-name">Last name</Label>
                <Input id="last-name" placeholder="Doe" required />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" type="email" placeholder="example@email.com" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="message">Message</Label>
              <Textarea id="message" placeholder="How can we help you?" className="min-h-[120px]" required />
            </div>
            <Button type="submit" className="w-full">
              Send message
            </Button>
          </form>
        </div>
      </div>
      <footer className="bg-background text-muted-foreground py-6 px-4 sm:px-6 w-full max-w-full order-last">
        <div className="container mx-auto max-w-5xl flex flex-col items-center gap-4 sm:flex-row sm:justify-between text-center sm:text-left">
          <p className="text-base sm:text-lg">&copy; 2024 New Salary Calculator. All rights reserved.</p>
          <nav className="flex gap-4">
            <Link href="#" className="text-base sm:text-lg hover:underline" prefetch={false}>
              Privacy
            </Link>
            <Link href="#" className="text-base sm:text-lg hover:underline" prefetch={false}>
              Terms
            </Link>
            <Link href="#" className="text-base sm:text-lg hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
        </div>
        <div className="container mx-auto max-w-5xl text-center mt-4">
          <p className="text-base sm:text-lg">
            <span>Designed by </span>
            <Link href="_https://arnavsingh.framer.ai" className="hover:underline" prefetch={false}>
              Arnav Singh
            </Link>
          </p>
        </div>
      </footer>
    </div>
  )
}
